package com.aura.filesys.dataobject;

public class FileInfoDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.user_name
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_name
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.user_name
     *
     * @return the value of file_info.user_name
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.user_name
     *
     * @param userName the value for file_info.user_name
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_name
     *
     * @return the value of file_info.file_name
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_name
     *
     * @param fileName the value for file_info.file_name
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}