package com.aura.filesys.dataobject;

public class FileInfoDO extends FileInfoDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.id
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_path
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_size
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    private Integer fileSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.id
     *
     * @return the value of file_info.id
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.id
     *
     * @param id the value for file_info.id
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_path
     *
     * @return the value of file_info.file_path
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_path
     *
     * @param filePath the value for file_info.file_path
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_size
     *
     * @return the value of file_info.file_size
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_size
     *
     * @param fileSize the value for file_info.file_size
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }
}