package com.aura.filesys.dao;

import com.aura.filesys.dataobject.FileInfoDO;
import com.aura.filesys.dataobject.FileInfoDOKey;

import java.util.List;

public interface FileInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    int deleteByPrimaryKey(FileInfoDOKey key);
    int deleteByFilePath(String filePath);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    int insert(FileInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    int insertSelective(FileInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    FileInfoDO selectByPrimaryKey(FileInfoDOKey key);
    List<FileInfoDO> selectByUserName(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    int updateByPrimaryKeySelective(FileInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbg.generated Tue Jul 02 19:48:03 CST 2019
     */
    int updateByPrimaryKey(FileInfoDO record);
}