package com.aura.filesys.dao;

import com.aura.filesys.dataobject.UserPswdDO;

public interface UserPswdDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Tue Jul 02 19:37:49 CST 2019
     */
    int deleteByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Tue Jul 02 19:37:49 CST 2019
     */
    int insert(UserPswdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Tue Jul 02 19:37:49 CST 2019
     */
    int insertSelective(UserPswdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Tue Jul 02 19:37:49 CST 2019
     */
    UserPswdDO selectByPrimaryKey(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Tue Jul 02 19:37:49 CST 2019
     */
    int updateByPrimaryKeySelective(UserPswdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Tue Jul 02 19:37:49 CST 2019
     */
    int updateByPrimaryKey(UserPswdDO record);
}